svgMap.prototype.counties = {
  CN: 'Cavan',
  CW: 'Carlow',
  CE: 'Clare',
  C: 'Cork',
  DL: 'Donegal',
  D: 'Dublin',
  G: 'Galway',
  KY: 'Kerry',
  KE: 'Kildare',
  KK: 'Kilkenny',
  LS: 'Laois',
  LM: 'Leitrim',
  LK: 'Limerick',
  LD: 'Longford',
  LH: 'Louth',
  MO: 'Mayo',
  MH: 'Meath',
  MN: 'Monaghan',
  OY: 'Offaly',
  RN: 'Roscommon',
  SO: 'Sligo',
  T: 'Tipperary',
  WD: 'Waterford',
  WH: 'Westmeath',
  WX: 'Wexford',
  WW: 'Wicklow',
  AM: 'Antrim',
  AH: 'Armagh',
  DY: 'Derry',
  DN: 'Down',
  FH: 'Fermanagh',
  TE: 'Tyrone',
};

